### PR TITLE
Add Minor Respondent Petitions

### LINKED ISSUE #117: Minor forms need to be implemented
When the respondent is an **unemancipated minor**, different petition and order forms need to be used. 
- Instead of CC 375, it's CC 375M
- Instead of CC 376, it's CC 376M
- and so on for CC 377, CC 380, CC 395, CC 396

These can all be found on the [SCAO](https://www.courts.michigan.gov/SCAO-forms/) site, or by googling for example "Michigan form CC 375M"

image

image

### LINKED ISSUE #214: collect respondent's parents' phone numbers?
In LHI, we don't collect respondent's parents' phone numbers, and we just put their addresses on the order forms:
image

Continue that, or start collecting phone like we currently have in Docassemble.

Also note, the parent info seems to be missing from the sexual assault order in LHI, though it was collected, is that intentional?
image

### LINKED ISSUE #218: Add kickout if respondent is < 10 years old
image

### PR DESCRIPTION
**Pull request by ekressmiller**
- Adds petitions for minor respondents, closes #117 
- Makes respondent parental information all optional, closes #214 
- Gets email sooner for ETC-required counties (to avoid confusion due to email being blank on Oakland contact info form at preview stage)
- Add kickout for respondents under 10, closes #218 
- Fixes some random template errors
- fixes bug in petitioner_respondent_relationship logic
- makes addresses display unit number on first line instead of separate line

### CODE REVIEW

**Comment by ekressmiller** [comment]
next steps: 
- spend no more than 30 minutes thinking if there's a simpler way to do the bundles with fresh brain
- add attachment blocks for new petitions
- test

**Comment by ekressmiller** [comment]
@RamiLorca, ready for review. Adding the minor petitions added a dimension to the basic PPO attachments and made the document logic more complicated. I stared at it for a while trying to figure out if there was a simpler way to build and enable/disable the bundles, but I couldn't come up with one. Please feel free to suggest something if you see a simpler way.

**Review by RamiLorca — CHANGES_REQUESTED** [review]
@ekressmiller - This might technically belong in a separate issue, but it's something I wanted to flag that came up as I was trying to generate the minor respondent docs. 

I ran through the domestic pathway as an adult user; made the respondent an unemancipated minor; and selected Oakland county. As soon as I got through all the questions about the respondent, I got the following error:
Screenshot 2024-11-21 at 6 10 30 PM

I took a closer look and it seems like the problem was coming from the following blocks, which led to the `'married'` option not being recognized since it was never appended to `relationship_choices`:
Error 1 Cause
Error Cause 2

I managed to get it working by adding an extra conditional logic layer in the interview order block. There may be a more graceful way to get the same effect, so feel free to change it up!
Solution 1

**Review by RamiLorca — CHANGES_REQUESTED** [review]
Minor nitpick, but I also noticed the font sizing some of the PDFs could use some tweaking. For example, the petitioner's address blocks came out pretty tiny:
Screenshot 2024-11-21 at 6 43 17 PM

**Comment by ekressmiller** [comment]
Thanks @RamiLorca ! Yeah, those address blocks are rough, will spend a little more time with them. Maybe I'll move the phone numbers over to the right side. I'll take a look at both the issues you identified on Monday and hopefully merge this one then.

**Pull request merged**
